### ISSUE TITLE
Override with Prismjs

### ISSUE THREAD

**Issue by ChristianChiarulli** [jamessimone/gatsby-remark-codefence#3]
It's possible I haven't read the docs close enough, but I was wondering if there was any way to override codefence with prismjs?

Like if I wanted some block to explicitly handled by prismjs but I loaded codefence first. Thanks.

**Comment by ChristianChiarulli** [comment]
nvm just noticed the only other issue 😆

**Comment by jamessimone** [comment]
@ChristianChiarulli haha no worries
