### ISSUE TITLE
Disabling Run button

### ISSUE THREAD

**Issue by ChristianChiarulli** [jamessimone/gatsby-remark-codefence#4]
Is this possible?

**Comment by jamessimone** [comment]
@ChristianChiarulli I would do this through CSS, unless it sounded like something a bunch of people were looking for. I would make the argument that the interactivity/runnable nature of codefence is what makes it so amazing. Otherwise, I would just use prism, for example.

**Comment by ChristianChiarulli** [comment]
right the only reason for disabling it would be because I don't have the
option to use prismjs currently.

**Comment by jamessimone** [comment]
@ChristianChiarulli if that's the case, I would simply target the output element that codefence creates with CSS:

```css
.compiler {
    display: none;
}
```

**Comment by ChristianChiarulli** [comment]
Just to be clear there is no way to currently use both correct?

**Comment by jamessimone** [comment]
That's correct. I may have time to work on the issue I opened myself this week, but it's a busy one for me so I wanted to put it out there in the event there was community interest on working on it, as well.

**Comment by ChristianChiarulli** [comment]
Ok I solved my issue, if you don't pass a lang it won't include the run button. Didn't know that. Closing.
