### ISSUE TITLE
How to disable Syntax Highlighting on codeblock

### ISSUE THREAD

**Issue by ayushxx7** [jamessimone/gatsby-remark-codefence#5]
I have some code blocks that just look off with the syntax highlight. Such as when I am writing about things you can do in Git.
I want to disable highlighting in such scenarios. What can be done?

Example
```
0d818eb HEAD@{0}: checkout: moving from master to test_branch
0d818eb HEAD@{1}: commit (amend): feat(Win): darcula theme for Powershell
6b1c0a7 HEAD@{2}: commit: feat(Win): darcula theme for Powershell
91fbc4c HEAD@{3}: commit: feat(Git): +blog: Reflog INIT
d98e625 HEAD@{4}: commit: feat(Python): numbers with fixed floating point
19e3184 HEAD@{5}: commit: feat(Python): bytes to human readable format
c7ca5db HEAD@{6}: commit: feat(Python): convert numbers to hexadecimal
c9c7021 HEAD@{7}: commit: feat(Python): restore timestamps after extraction
```

Looks Like this:
![image](https://user-images.githubusercontent.com/16764027/115109193-f4bc7d80-9f91-11eb-8698-267771a60484.png)

Moreover, is there a way to add `Git` and `Vim` Syntax Highlighting to `codefence` blocks?

Thank you for writing this plugin!

**Comment by jamessimone** [comment]
Hi there,

I’m really glad you like using the code fence plugin. It was a fun pandemic distraction to author. Unfortunately, syntax highlighting and such is handled by codefence itself — I would recommend you reach out to the author at https://codefence.io/ (I don’t believe there is a GitHub; they just have a contact link on the site).

Thank you, and good luck!

James

**Comment by jamessimone** [comment]
Closing, as the issue stems from Codefence itself and not the plugin.
